---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: devopscoop
  namespace: default
spec:
  interval: 60m
  type: "oci"
  url: oci://registry.gitlab.com/devopscoop/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 60m
  type: "oci"
  url: oci://registry-1.docker.io/bitnamicharts/
