apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: app1
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: app1
  policy:
    numerical:
      order: asc
