# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app1
resources:
  - namespace.yaml

  # Calling the secret from this Kustomization, so it will create it in this namespace.
  # - ../gitlab-auth.secret.yaml

  - release.yaml
  - evanstest.yaml
